/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // guidesSidebar: [
  //   {
  //     type: 'category',
  //     label: 'User Guides',
  //     items: [
  //       'docs/guides/index', // Custom index.mdx file
  //       // Add other files in the same section here if needed
  //       'getting-started-with-eyer/guides/doc1',
  //       'getting-started-with-eyer/guides/doc2',
  //       // etc.
  //     ],
  //   },
  // ],
};

export default sidebars;
